// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCckMzoyxqz8JiNLOE9MCGRA4BX4Hs10CA',
    appId: '1:611740478041:web:dcc0d1f938f3c2007e1f48',
    messagingSenderId: '611740478041',
    projectId: 'pushnotificationstestin',
    authDomain: 'pushnotificationstestin.firebaseapp.com',
    storageBucket: 'pushnotificationstestin.appspot.com',
    measurementId: 'G-8JDEV2JCLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCPfF-sp1lraWNhqBQJEbW2VDvmOvidPo',
    appId: '1:611740478041:android:105257b3589b1ea87e1f48',
    messagingSenderId: '611740478041',
    projectId: 'pushnotificationstestin',
    storageBucket: 'pushnotificationstestin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDklXxhi65M7f5MvpuRwXy73btV9bb9hZQ',
    appId: '1:611740478041:ios:b9026612adfd47867e1f48',
    messagingSenderId: '611740478041',
    projectId: 'pushnotificationstestin',
    storageBucket: 'pushnotificationstestin.appspot.com',
    iosClientId: '611740478041-30vqqcj9i1b438q2dldggp3h45om9boe.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDklXxhi65M7f5MvpuRwXy73btV9bb9hZQ',
    appId: '1:611740478041:ios:3f19ccae7f0ceb277e1f48',
    messagingSenderId: '611740478041',
    projectId: 'pushnotificationstestin',
    storageBucket: 'pushnotificationstestin.appspot.com',
    iosClientId: '611740478041-uh5t6fdsvurbarsahv8esd5imv14gfip.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationsApp.RunnerTests',
  );
}
